export const PDP_HEADER = 'PDP Header';
export const PRODUCT_IMAGES = 'Product Images';
export const PDP_PRICE_AND_QUANTITY = 'PDP_PRICE_AND_QUANTITY';
export const PDP_USP = 'PDP_USP';
export const PDP_MORE_OPTIONS = 'PDP_MORE_OPTIONS';
export const GROUPED_PRODUCTS = 'GROUPED_PRODUCTS';
export const GLOBAL_OFFER_BANNER = 'GLOBAL_OFFER_BANNER';
export const HTML_COMPONENT = 'HTML_COMPONENT';
export const PDP_3D_COMPONENT = 'PDP_3D_COMPONENT';
export const RECOMMENDATION_WIDGET_OFTEN_BROUGHT_TOGETHER =
  'RECOMMENDATION_WIDGET_OFTEN_BROUGHT_TOGETHER';
export const RECOMMENDATION_WIDGET_YOU_MAY_ALSO_LIKE =
  'RECOMMENDATION_WIDGET_YOU_MAY_ALSO_LIKE';
export const A1_COMPONENT = 'A1_COMPONENT';
export const PDP_PRODUCT_FEATURES_DESCRIPTION =
  'PDP_PRODUCT_FEATURES_DESCRIPTION';
export const PDP_CLICK_AND_COLLECT_STRIP = 'PDP_CLICK_AND_COLLECT_STRIP';
export const PDP_BULK_ORDERS_STRIP = 'PDP_BULK_ORDERS_STRIP';
export const RECOMMENDATION_WIDGET_SIMILAR_PRODUCTS =
  'RECOMMENDATION_WIDGET_SIMILAR_PRODUCTS';
export const RECOMMENDATION_WIDGET_CUSTOMER_ALSO_BOUGHTED =
  'RECOMMENDATION_WIDGET_CUSTOMER_ALSO_BOUGHTED';
export const PDP_BUY_NOW_PAY_LATER = 'PDP_BUY_NOW_PAY_LATER';
