workflows:
  react-native-android:
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini
    environment:
      node: 16.16.0
      groups:
        - keystore_credentials
        - firebase # <-- (Includes FIREBASE_TOKEN)
        # - google_play
      vars:
        PACKAGE_NAME: 'com.app.danubehomeonline'
    scripts:
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
      - name: Install yarn dependencies
        script: |
          rm -rf node_modules/ && rm -rf package-lock.json && rm -rf yarn.lock && yarn install
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      # - name: Build Android release
      #   script: |
      #     cd android && ./gradlew bundleRelease
      - name: Build Android Apk
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      # - android/app/build/**/outputs/bundle/**/*.aab
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN
        # OR: firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: 1:518182504998:android:7d55f3e93513197bafb4e7 # Add your iOS app id retrieved from Firebase console
          groups: # Add one or more groups that you wish to distribute your iOS application to, you can create groups in the Firebase console
            - dh_internal
      email:
        recipients:
          - dhaval.appdeveloper@gmail.com
          - shameem.kt@gmail.com
        notify:
          success: true
          failure: false

  react-native-ios:
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $CM_BUILD_DIR/node_modules
    name: Danube Home Mobile App iOS
    max_build_duration: 120
    instance_type: mac_mini
    environment:
      groups:
        - appstore_credentials # <-- (Includes APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY, CERTIFICATE_PRIVATE_KEY) - https://docs.codemagic.io/code-signing-yaml/signing-ios/
        - ios_config # <-- (Includes APP_STORE_APP_ID - Put the app id number here. This is found in App Store Connect > App > General > App Information)
        - firebase # <-- (Includes FIREBASE_TOKEN)
      # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
      vars:
        XCODE_WORKSPACE: 'danubehomeonline.xcworkspace' # <-- Put the name of your Xcode workspace here
        XCODE_SCHEME: 'danubehomeonline' # <-- Put the name of your Xcode scheme here
        BUNDLE_ID: 'com.aldanube.dehome' # <-- Put your Bundle Id here e.g com.domain.myapp
      node: v16.15.0
      xcode: 13.2.1
      cocoapods: default
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: feature/new-architecture
          include: true
          source: true
    scripts:
      - name: Install yarn dependencies
        script: |
          yarn install
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: app-store-connect
        script: |
          # For information about Codemagic CLI commands visit: https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/README.md
          # For details about the --type paramater below - https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/fetch-signing-files.md#--typeios_app_adhoc--ios_app_development--ios_app_inhouse--ios_app_store--mac_app_development--mac_app_direct--mac_app_store--mac_catalyst_app_development--mac_catalyst_app_direct--mac_catalyst_app_store--tvos_app_adhoc--tvos_app_development--tvos_app_inhouse--tvos_app_store
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Increment build number
        script: |
          #!/bin/sh
          set -e
          set -x
          cd $CM_BUILD_DIR/ios
          # agvtool new-version -all $(($BUILD_NUMBER + 1))
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles --warn-only
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/yaml-publishing/email
      email:
        recipients:
          - shameem.kt@gmail.com
          - ibrahim.shameem@danubehome.com
          - abdul.bari@danubehome.com
        notify:
          success: true # To not receive a notification when a build succeeds
          failure: true # To not receive a notification when a build fails
      slack:
        # See the following link about how to connect your Slack account - https://docs.codemagic.io/yaml-publishing/slack
        channel: '#mobile-app'
        notify_on_build_start: true # To receive a notification when a build starts
        notify:
          success: true # To receive a notification when a build succeeds
          failure: true # To not receive a notification when a build fails
      firebase:
        firebase_token: $FIREBASE_TOKEN
        # OR: firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        ios:
          app_id: 1:518182504998:ios:8cd2f484c7af4809afb4e7 # Add your iOS app id retrieved from Firebase console
          groups: # Add one or more groups that you wish to distribute your iOS application to, you can create groups in the Firebase console
            - dh_internal
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY # Contents of the API key, can also reference environment variable such as $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER # Alphanumeric value that identifies the API key, can also reference environment variable such as $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID # Alphanumeric value that identifies who created the API key, can also reference environment variable such as $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true # Optional boolean, defaults to false. Whether or not to submit the uploaded build to TestFlight to automatically enroll your build to beta testers.
