import { EVENT_NAME_SCREEN_VIEW, EVENT_NAME_SCREEN_VIEW_COMPLETE } from '.';

export const ADJUST_EVENT_TOKEN_MAPPPING = {
  app_att: 'bgxadg',
  [EVENT_NAME_SCREEN_VIEW_COMPLETE]: 'tpm40f',
  [EVENT_NAME_SCREEN_VIEW]: 'tpm40f',
};
